apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharded-counter
  labels:
    app: sharded-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharded-counter
  template:
    metadata:
      labels:
        app: sharded-counter
    spec:
      containers:
        - name: sharded-counter
          image: sagar10018233/sharded-counter:latest
          ports:
            - containerPort: 8080
          env:
            - name: ETCD_ENDPOINTS
              value: "http://etcd-service.default.svc.cluster.local:2379"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PORT
              value: "8080"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: sharded-counter
spec:
  selector:
    app: sharded-counter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None
  type: ClusterIP
