apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharded-counter-app
  labels:
    app: sharded-counter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharded-counter-app
  template:
    metadata:
      labels:
        app: sharded-counter-app
    spec:
      containers:
        - name: sharded-counter-app
          image: sagar10018233/sharded-counter:latest
          ports:
            - containerPort: 8080
          env:
            - name: ETCD_ENDPOINTS
              value: "http://etcd-service.default.svc.cluster.local:2379"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PORT
              value: "8080"
            - name: SHARD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SHARD_SERVICE_NAME
              value: "sharded-counter-shards"
            - name: SERVICE_TYPE
              value: "app"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"